package model.pojo;
// Generated 2018/5/8 下午 04:08:19 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Nurseworkspace generated by hbm2java
 */
public class Nurseworkspace  implements java.io.Serializable {


     private Integer id;
     private int nurseId;
     private int workSpaceId;
     private Date crtTime;

    public Nurseworkspace() {
    }

    public Nurseworkspace(int nurseId, int workSpaceId, Date crtTime) {
       this.nurseId = nurseId;
       this.workSpaceId = workSpaceId;
       this.crtTime = crtTime;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getNurseId() {
        return this.nurseId;
    }
    
    public void setNurseId(int nurseId) {
        this.nurseId = nurseId;
    }
    public int getWorkSpaceId() {
        return this.workSpaceId;
    }
    
    public void setWorkSpaceId(int workSpaceId) {
        this.workSpaceId = workSpaceId;
    }
    public Date getCrtTime() {
        return this.crtTime;
    }
    
    public void setCrtTime(Date crtTime) {
        this.crtTime = crtTime;
    }




}


