package model.pojo;
// Generated 2018/5/8 下午 04:08:19 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Nurse generated by hbm2java
 */
public class Nurse  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String status;
     private Date crtTime;
     private String nurseId;
     private Date uptTime;

    public Nurse() {
    }

	
    public Nurse(String name, String status, Date crtTime, String nurseId) {
        this.name = name;
        this.status = status;
        this.crtTime = crtTime;
        this.nurseId = nurseId;
    }
    public Nurse(String name, String status, Date crtTime, String nurseId, Date uptTime) {
       this.name = name;
       this.status = status;
       this.crtTime = crtTime;
       this.nurseId = nurseId;
       this.uptTime = uptTime;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getCrtTime() {
        return this.crtTime;
    }
    
    public void setCrtTime(Date crtTime) {
        this.crtTime = crtTime;
    }
    public String getNurseId() {
        return this.nurseId;
    }
    
    public void setNurseId(String nurseId) {
        this.nurseId = nurseId;
    }
    public Date getUptTime() {
        return this.uptTime;
    }
    
    public void setUptTime(Date uptTime) {
        this.uptTime = uptTime;
    }




}


